
//  THIS CLASS IS INTENDED FOR MANUAL TESTING ONLY (NOT FOR REAL LOGIC !)
//  DO NOT CALL THIS CLASS OUTSIDE THIS PACKAGE 
//  DO NOT TOUCH NOR OVERRIDE METHODS IN THIS CLASS

final class MainTest{
    public static void main(String args[]){
        // EXECUTE BUISNESS LOGIC METHODS HERE
    }

    // IMPLEMENT THE TESTING HERE

    // BREAK ENCAPSULATION HERE (DO NOT USE THIS OUTSIDE THIS CLASS)

    // USE ASSERT HERE

    // THROW ASSERT_ERROR OR RUN_TIME_EXCEPTION IF TESTING FAILS

    // ADD STATIC METHODS IN UTILS FOR BETTER DISPLAY (FORMATTING INPUT)
}