USE BIBLIOTHEQUEDB;     --  <---   nom de la BD 

CREATE TABLE CLIENT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR (50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    email VARCHAR (50) UNIQUE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ADMINS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR (50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    email VARCHAR (50) UNIQUE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LIVRE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    titre VARCHAR (100) NOT NULL,
    auteur VARCHAR (100) UNIQUE,
    categorie VARCHAR (100) UNIQUE
);

CREATE TABLE EMPRUNT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    date_emprunt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_retour TIMESTAMP ,
    date_limit TIMESTAMP ,
    livre_id INT,
    FOREIGN KEY (livre_id) REFERENCES LIVRE(id)
);

INSERT INTO CLIENT(username, password, email)
    VALUES  ();

INSERT INTO ADMINS(username, password, email)
    VALUES  ();

INSERT INTO LIVRE(titre, auteur, categorie)
    VALUES  ();

INSERT INTO EMPRUNT(date_retour, date_limit)
    VALUES  ();




--  Use these to check tables

SELECT * FROM CLIENT;
SELECT * FROM ADMINS;
SELECT * FROM LIVRE;
SELECT * FROM EMPRUNT;




--  DO NOT USE THESE UNLESS RESETTING THE ENTIRE TABLE
TRUNCATE TABLE CLIENT;
TRUNCATE TABLE ADMINS;
TRUNCATE TABLE LIVRE;
TRUNCATE TABLE EMPRUNT;


